### ISSUE TITLE
Build Error on macOS

### ISSUE THREAD

**Issue by lenkite** [Alairion/not-enough-standards#2]
Was this tested on macOS ? Because there is a build error on macOS when attempting to consume process.hpp

```
not-enough-standards-src/include/nes/process.hpp:44:14: fatal error: wait.h: No such file or directory
   44 |     #include <wait.h>
```

I thought on macOS (and FreeBSD) this header should be `<sys/wait.h>`.  I checked my  Xcode header directory and also confirmed this is at sys/wait.h

```
cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
MacOSX.sdk ➤ fd wait.h                                                                                                                                                                                               
usr/include/sys/wait.h
```

**Comment by Alairion** [comment]
Hi, it seems that the header is actually `sys/wait.h` on every system, I only tested it on Linux (Debian 9) and the path was OK, I'm gonna double check that for every file and correct invalid include paths everywhere. Thank you for report.
